[mypy]
# Включает строгий режим (проверяет всё максимально жестко)
strict = True

# Игнорировать ошибки импорта для библиотек, у которых нет хинтов (например, старые версии PyYAML)
ignore_missing_imports = True

# Показывать коды ошибок (полезно, чтобы точечно отключать предупреждения)
show_error_codes = True

# Исключаем из анализа ненужные папки
exclude = ^(src/examples|src/ai_src)/
